### PR TITLE
edited locale to be 8 characters max

### PR DESCRIPTION
**Pull request by adamzwakk**
Added this to allow for longer locales such as:

shi-Tfng
zh-hant
zh-hans

### CODE REVIEW

**Comment by sildraug** [comment]
I'm sorry but your pull request breaks the tests.

**Comment by nickescobedo** [comment]
Is there a reason to not allow locales longer than 6 characters?

**Comment by sildraug** [comment]
Locales allow up to 10 chars.

**Comment by nickescobedo** [comment]
Why not allow 10 characters then?

**Pull request closed without merging**
