### PR TITLE
Update Dependancy Versions

### PR DESCRIPTION
**Pull request by thetomcake**
The unit tests pass (with 1 failure which was failing with 5.1.x) and having implemented and tested on a laravel 5.2 installation all appears to be working correctly.

### CODE REVIEW

**Comment by sildraug** [comment]
Hi Tom,

Thank you for your pull request. I've fixed the migrations issue and added 5.2 compatibility in a different way on version 2.1.4. I don't quite get what you did with the translatable trait. Could you explain what the use case is?

Thank you!

**Comment by thetomcake** [comment]
Hey,

I wasn't intending to push the translatable trait back into the main repo as the solution is not ideal and would require additional work, I will explain what I did however.

When saving the field123_translated field the field123 field value is the same as the last saved language. The change I made always stores the fallback locales value in the field123 field. However it does not check to see if the value has changed before updating as it did previously so it is not ideal.

The reason for this was to allow easier searching using LIKE SQL clauses in default locale. It was a bit of a dirty solution to a requirement I had for a project. A better solution would most likely be elasticsearch or similar.

Thank you for your reply,
Tom.

**Comment by sildraug** [comment]
Hi Tom,

The way we use the translatable field, we never save the model with text in a language different from the default one. In fact, if you do, you would be overwritting the default language entry. Maybe if you tell me a bit more about your use case I could help you.

**Comment by thetomcake** [comment]
Hi,

Sorry for the slow reply. Using the default Translatable trait, the last value saved in whatever language saves in the actual field.

The example here is a title field that is saved in english, then saved in welsh and shows the different table values and the translation table after both saves.

Please let me know if I have misunderstood this or it is intended functionality.
2016-03-18-171640_1526x692_scrot

**Comment by sildraug** [comment]
This is intended. Sorry I missed the reply!

**Pull request closed without merging**
